#!/bin/bash

echo "Modifying ts3db_mariadb.ini with following info:
Host=$TS3DB_PORT_3306_TCP_ADDR,
Port=$TS3DB_PORT_3306_TCP_PORT,
Database=$TS3_MARIADB_DB,
Username=$TS3_MARIADB_USER,
Password=$TS3_MARIADB_PASS"

cat > /opt/teamspeak/ts3db_mariadb.ini <<-EOF
[config]
host=$(DB_PORT_3306_TCP_ADDR)
port=$(DB_PORT_3306_TCP_PORT)
username=$(DB_USER)
password=$(DB_PASSWORD)
database=$(DB_NAME)
socket=
EOF

# Run Teamspeak server
cd /opt/teamspeak && ./ts3server_minimal_runscript.sh inifile=ts3server.ini
